// openc3/templates/tool_svelte/src/App.svelte
<div style="min-width: 100px;">
  <Card variant="outlined" padded>
    <Button on:click={() => handleClick()} variant="raised">
      <Label>Send Command</Label>
    </Button>
  </Card>
</div>

<Portal target="#openc3-menu">
  <Button on:click={() => menu.setOpen(true)} variant="raised">
    <Label>File</Label>
  </Button>
  <Menu bind:this={menu}>
    <List>
      <Item on:SMUI:action={() => handleClick()}>
        <Text>Send Command</Text>
      </Item>
    </List>
  </Menu>

  <div style="display: inline-block; text-align: center; width:80%;"><%= tool_name_display %></div>
</Portal>

<script>
  import Portal from "svelte-portal";
  import Menu from '@smui/menu';
  import List, { Item, Separator, Text } from '@smui/list';
  import Button, { Label } from '@smui/button';
  import Card from '@smui/card';
  import { OpenC3Api } from '@openc3/js-common/services';

  let menu;

  function handleClick () {
    let api = new OpenC3Api();
    api.cmd("INST", "COLLECT", { TYPE: "NORMAL" }).then((response) => {
      alert("Command Sent!");
    });
	}

  document.title = "<%= tool_name_display %>";
</script>

// openc3/templates/tool_angular/src/app/app.component.ts
import { Component, ViewChild, AfterViewInit, OnDestroy } from '@angular/core';
import {CdkPortal, DomPortalOutlet} from '@angular/cdk/portal';
import { OpenC3Api } from "@openc3/js-common/services";

@Component({
  selector: 'openc3-tool-<%= tool_name %>-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements  AfterViewInit, OnDestroy {
  @ViewChild(CdkPortal)
  private portal: CdkPortal | undefined;
  private host: DomPortalOutlet | undefined;

  clickHandler = function() {
    let api = new OpenC3Api();
    api.cmd("INST", "COLLECT", { TYPE: "NORMAL" }).then((response: any) => {
      alert("Command Sent!");
    });
  }
  getMenuElement() {
    let elem = document.getElementById("openc3-menu")
    if (elem) {
      return elem
    } else {
      return new HTMLElement()
    }
  }
  ngAfterViewInit(): void {
    this.host = new DomPortalOutlet(
      this.getMenuElement()
    );
    this.host.attach(this.portal);
    document.title = "<%= tool_name_display %>";
    let tool = document.querySelector('#openc3-tool');
    if (tool == null) {
      tool = new HTMLElement()
    }
    let overlay = document.querySelector('.cdk-overlay-container');
    if (overlay == null) {
      overlay = new HTMLElement()
    }
    // Move stuff
    tool.append(overlay);
  }
  ngOnDestroy(): void {
    if (this.host) {
      this.host.detach();
    }
  }
}

<!-- This menu position hack should only be necessary in the portal -->
<style>
::ng-deep .mat-mdc-menu-panel.myMenu {
  background-color:white;
  color:black;
  position:absolute !important;
  top:0px;
  left:60px;
}

.mat-mdc-card {
  background: white;
}
</style>

<div class="content" role="main">

  <mat-card color="accent">
    <mat-card-content><button mat-raised-button color="primary" (click)="clickHandler()">Send Command</button></mat-card-content>
  </mat-card>

  <ng-template cdk-portal>
    <button mat-raised-button [matMenuTriggerFor]="menu">File</button>
    <mat-menu #menu="matMenu" class="myMenu">
      <button mat-menu-item (click)="clickHandler()">Send Command</button>
    </mat-menu>
    <div style="display: inline-block; width: 80%; text-align: center"><%= tool_name_display %></div>
  </ng-template>
</div>

<router-outlet></router-outlet>
